/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Menu_controller;
import controlador.Nivel_controller;
import entidades.Nivel;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author darkpastiursSennin
 */
public class frmPermisosNiveles extends javax.swing.JDialog {

    Validaciones validar = new Validaciones();
    List<Nivel> niveles = new ArrayList<>();
    Nivel_controller nivel_controlador = new Nivel_controller();
    Menu_controller menu_controlador = new Menu_controller();
    List<JCheckBox> chks = new ArrayList<>();
    int colIndex = 10;
    int rowIndex = 10;
    int contador = 0;
    /**
     * Creates new form frmPermisosNiveles
     *
     * @param parent
     * @param modal
     */
    public frmPermisosNiveles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        niveles = nivel_controlador.Obtener(true);
        validar.cargarNiveles(cboNiveles, niveles);

    }

    void llenarPermisos(Nivel lvl) {        
        if (lvl.getMenus().isEmpty()) {
            lvl.setMenus(menu_controlador.Obtener());
        }          
        JPanel jpPermisos = new JPanel();
        jpPermisos.setBounds(tbpPasos.getBounds());
        jpPermisos.setLayout(null);
        jpPermisos.setName("Opciones");
        JCheckBox selAll = new JCheckBox("Seleccionar todo");
        selAll.setBounds(10, 10, 300, 25);
        rowIndex += 20;
        jpPermisos.add(selAll);
        lvl.getMenus().stream().forEach(menu -> {            
            JCheckBox chk = new JCheckBox();
            chk.setText(menu.getNombre());
            if(menu.isPermiso()){
                contador++;
            }
            chk.setSelected(menu.isPermiso());
            chk.setBounds(colIndex, rowIndex, 200, 25);
            if(rowIndex > (jpPermisos.getBounds().height - 100)){
                rowIndex = 30;
                colIndex += 200;
            } else {                
                rowIndex += 20;
            }
            chks.add(chk);
            jpPermisos.add(chk);
        });
        colIndex = 10;   
        rowIndex = 10;
        if(contador == lvl.getMenus().size()){
            selAll.setSelected(true);
            contador = 0;
        }
        ActionListener changeState;
        changeState = (ActionEvent evt) -> {
            AbstractButton buttom = (AbstractButton) evt.getSource();
            for(Component comp : jpPermisos.getComponents()){
                if(comp instanceof JCheckBox){
                    ((JCheckBox) comp).setSelected(buttom.getModel().isSelected());
                }
            }
        };
        selAll.addActionListener(changeState);
        this.tbpPasos.add(jpPermisos);
    }
    
    void vaciarPermisos(){
        for (int i = 0; i < tbpPasos.getTabCount(); i++) {
            if(tbpPasos.getTitleAt(i).equals("Opciones"))
                tbpPasos.remove(i);        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpPasos = new javax.swing.JTabbedPane();
        jpTab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboNiveles = new javax.swing.JComboBox<>();
        jpBotones = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administracion de Permisos - Sistema de Compra y Venta");
        setResizable(false);

        tbpPasos.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tbpPasos.setToolTipText("");
        tbpPasos.setEnabled(false);
        tbpPasos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbpPasosStateChanged(evt);
            }
        });

        jLabel1.setText("Seleccionar Nivel:");

        javax.swing.GroupLayout jpTab1Layout = new javax.swing.GroupLayout(jpTab1);
        jpTab1.setLayout(jpTab1Layout);
        jpTab1Layout.setHorizontalGroup(
            jpTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(cboNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jpTab1Layout.setVerticalGroup(
            jpTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTab1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jpTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        tbpPasos.addTab("Seleccionar Nivel", jpTab1);

        btnAnterior.setText("Anterior");
        btnAnterior.setEnabled(false);
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnterior)
                .addGap(88, 88, 88)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(75, 75, 75)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );
        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbpPasos, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpPasos, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbpPasos.getAccessibleContext().setAccessibleName("Seleccionar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        btnSiguiente.setEnabled(false);
        btnAnterior.setEnabled(true);
        btnGuardar.setEnabled(true);
        llenarPermisos((Nivel) cboNiveles.getSelectedItem());       
        tbpPasos.setSelectedIndex(1);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        btnSiguiente.setEnabled(true);
        btnAnterior.setEnabled(false);
        btnGuardar.setEnabled(false);
        chks.clear();
        tbpPasos.setSelectedIndex(0);
        vaciarPermisos();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Nivel lvl = (Nivel) cboNiveles.getSelectedItem();
        boolean exito = false;
        if (!lvl.getMenus().isEmpty()) {
            for (int i = 0; i < lvl.getMenus().size(); i++) {
                lvl.getMenus().get(i).setPermiso(chks.get(i).isSelected());
                exito = menu_controlador.Editar(lvl.getMenus().get(i), lvl);
            }
        } else {            
            lvl.setMenus(menu_controlador.Obtener());
            for (int i = 0; i < lvl.getMenus().size(); i++) {
                lvl.getMenus().get(i).setPermiso(chks.get(i).isSelected());
                exito = menu_controlador.Registrar(lvl.getMenus().get(i), lvl);
            }
        }
        
        if (exito) {
            JOptionPane.showMessageDialog(
                    null,
                    "Se han registrado los permisos con exito",
                    "Sistema de Compras y Ventas - Permisos",
                    JOptionPane.INFORMATION_MESSAGE
            );
            tbpPasos.setSelectedIndex(0);
            btnSiguiente.setEnabled(true);
            btnAnterior.setEnabled(false);
            btnGuardar.setEnabled(false);
            chks.clear();
            tbpPasos.setSelectedIndex(0);
            vaciarPermisos();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tbpPasosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbpPasosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpPasosStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPermisosNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPermisosNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPermisosNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPermisosNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPermisosNiveles dialog = new frmPermisosNiveles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cboNiveles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpTab1;
    private javax.swing.JTabbedPane tbpPasos;
    // End of variables declaration//GEN-END:variables
}
